Develop
undina13/java-explore-with-me pull request #1
Opened 2022-10-02 12:58 UTC by undina13

2022-10-03 15:06 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к работе, если что приходите ко мне в Slack.

2022-10-03 15:06 UTC, Frilock commented on README.md
>  Template repository for ExploreWithMe project.
Смотрите сразу пару комментариев, у Вас 43 коммита, большинство из которых имеет странное название не несущее никакой смысловой нагрузки. Предлагаю такие коммиты сквашить (объединять). Заодно потренируетесь с такими фичами от гита как rebase, например.

Кроме того, смотрите, у Вас в задании в Readme нужно ссылку разместить это ок, но я еще предлагаю в этом файле указывать кратко основную информацию о проекте: 1. Как запускается, как собирается 2. Основные модули, что какой делает 3. Если есть специфические конфиги - информация о них

2022-10-03 15:06 UTC, Frilock commented on stats_server/src/main/java/ru/practicum/stats_server/HitMapper.java
> +package ru.practicum.stats_server;
Мне кажется если Вы начали придерживаться идеи о размещении всех файлов в разных пакетах, то и данный класс нужно сунуть в пакет mapper/mappers

2022-10-03 15:06 UTC, Frilock commented on stats_server/src/main/java/ru/practicum/stats_server/repository/HitRepository.java
> +
Лишние строчки после методов

2022-10-03 15:06 UTC, Frilock commented on stats_server/src/main/java/ru/practicum/stats_server/model/HitModel.java
> +    @Column(name = "app")
Смотрите, это общий комментарий, который ко всем классам модели относится. У Вас вот есть в ресурсах файл где вы задаете поля. Так вот, я посмотрел Вы либо используете размер 256, либо 512, во первых, на мой взгляд, нужно к размерам полей отнестись более рационально, подумать, что, например, для поля code - 256 символов не нужно и хватит 50, а для поля description - 256 символом может быть мало и нужно задать, например, 1000. То есть хочу от Вас чтобы размерность полей была продумана. 

Далее, смотрите в аннотации Column, лучше указывать размерность аналогичную той, что у Вас в скриптах, так же другие флаги, например, nullable = false.

2022-10-03 15:06 UTC, Frilock commented on stats_server/src/main/java/ru/practicum/stats_server/model/HitModel.java
> +@Data
Вообще при использовании data-jpa лучше equals и hashCode реализовать самим, без данной аннотации, иначе могут быть проблемы в дальнейшем. (можете с помощью IDEA сгенерировать методы: code - generate ...)

2022-10-03 15:06 UTC, Frilock commented on stats_server/src/main/java/ru/practicum/stats_server/service/HitService.java
> +    public List<ViewStats> getViewStats(String start, String end, List<String> uris, Boolean unique) throws UnsupportedEncodingException {
throws UnsupportedEncodingException - можно не писать, так как вы в контролере все равно его дальше пробрасываете.

2022-10-03 15:06 UTC, Frilock commented on stats_server/src/main/java/ru/practicum/stats_server/service/HitService.java
> +            if (unique) {
Еще советую установить плагин sonarlint. Это статический анализатор кода, он подскажет ряд тонких мест и некоторые хорошие практики, например, тут:
Use the primitive boolean expression here.

2022-10-03 15:06 UTC, Frilock commented on stats_server/src/main/java/ru/practicum/stats_server/HitMapper.java
> +                .timestamp(LocalDateTime.parse(endpointHit.getTimestamp(),
Смотрю реализацию метода parse и вот там параметры помечены как not null. А по логике приложения вроде как могут прийти null параметры и тут будет NPE. Мне кажется либо нужно на ДТОшках делать валидацию и в лидировать данные, либо в мапперах проверять такие места, где может быть NPE. Проверьте похожие места, пожалуйста, тоже

2022-10-03 15:06 UTC, Frilock commented on stats_server/src/main/java/ru/practicum/stats_server/service/HitService.java
> +    public EndpointHit createHit(EndpointHit endpointHit) {
Знаю, что это у Вас не обязательное требование, но вообще хочется на Ваш код видеть unit тесты, поскольку на любой работе, где даже есть авто тесты в проектах, Вас все равно будут просить писать юниты для тестирования/покрытия своего кода.

2022-10-03 15:06 UTC, Frilock commented on stats_server/.gitignore
> +HELP.md
По моему на проект достаточно одного корневого gitignore файла, хотя это не принципиально

2022-10-03 15:06 UTC, Frilock commented on main_server/src/main/java/ru/practicum/main_server/client/BaseClient.java
> +            if (parameters != null) {
Можно заменить на тернарное выражение: условие ? выражение1 : выражение2

2022-10-03 15:06 UTC, Frilock commented on main_server/src/main/java/ru/practicum/main_server/controller/CategoryController.java
> +    @GetMapping()
Пустые скобки можно не ставить

2022-10-03 15:06 UTC, Frilock commented on main_server/src/main/java/ru/practicum/main_server/controller/ExceptionHandlers.java
> +                .reason("object not found")
Строку более одного раза используете, можете в классе создать константу private static final String REASON_MESSAGE ...

2022-10-03 15:06 UTC, Frilock commented on main_server/src/main/java/ru/practicum/main_server/dto/NewCategoryDto.java
> +    private String name;
Странный какой то объект из одного поля, для чего он Вам?

2022-10-03 15:06 UTC, Frilock commented on main_server/src/main/java/ru/practicum/main_server/model/Location.java
> +
Лишняя пустая строка

2022-10-03 15:06 UTC, Frilock commented on main_server/src/main/java/ru/practicum/main_server/model/Participation.java
> +
Лишняя пустая строка

2022-10-03 15:06 UTC, Frilock commented on main_server/src/main/java/ru/practicum/main_server/model/User.java
> +
Лишняя пустая строка

2022-10-03 15:06 UTC, Frilock commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +    public EventService(EventRepository eventRepository, ParticipationRepository participationRepository, HitClient hitClient, UserService userService, CategoryRepository categoryRepository, Location
Слишком длинная строка, либо переносите аргументы, либо как вариант можно повесить на класс аннотацию RequiredArgsConstructor и тогда можно его будет убрать

2022-10-03 15:06 UTC, Frilock commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +        if (rangeStart == null) {
Можно на тернарник заменить условие

2022-10-03 15:06 UTC, Frilock commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +        if (!(dto.getState().equals(State.PUBLISHED.toString()))) {
Вообще enum поля лучше сравнивать через обычные операторы != и ==, поскольку работать будет и так и так, но обычные операторы как минимум быстрее

2022-10-03 15:06 UTC, Frilock commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +        if (adminUpdateEventRequest.getAnnotation() != null) {
Вообще, чтобы таких ифов много не делать можно писать так 

Optional.ofNullable(updateEventRequest.getAnnotation())
                .ifPresent(event::setAnnotation);

2022-10-03 15:06 UTC, Frilock commented on main_server/src/main/java/ru/practicum/main_server/service/ParticipationService.java
> +        if (userId.equals(participation.getRequester().getId())) {
participation.getRequester() не вернет null? Иначе NPE получите. Дабы избегать таких проблем предлагаю пользоваться null safe equals - Objects.equals(01,02)

Проверьте похожие места

2022-10-07 09:53 UTC, undina13 commented on README.md
>  Template repository for ExploreWithMe project.
получилось) магия, не иначе) спасибо, что подсказали)

2022-10-07 09:54 UTC, undina13 commented on stats_server/src/main/java/ru/practicum/stats_server/HitMapper.java
> +package ru.practicum.stats_server;
готово

2022-10-07 09:55 UTC, undina13 commented on stats_server/src/main/java/ru/practicum/stats_server/repository/HitRepository.java
> +
готово

2022-10-07 10:27 UTC, undina13 commented on stats_server/src/main/java/ru/practicum/stats_server/model/HitModel.java
> +    @Column(name = "app")
готово, спасибо, что обратили внимание

2022-10-07 10:28 UTC, undina13 commented on stats_server/src/main/java/ru/practicum/stats_server/model/HitModel.java
> +@Data
спасибо, поняла, исправила

2022-10-09 06:19 UTC, undina13 commented on stats_server/src/main/java/ru/practicum/stats_server/service/HitService.java
> +    public List<ViewStats> getViewStats(String start, String end, List<String> uris, Boolean unique) throws UnsupportedEncodingException {
fix

2022-10-09 06:26 UTC, undina13 commented on stats_server/src/main/java/ru/practicum/stats_server/service/HitService.java
> +            if (unique) {
готово, интересная штука, спасибо.

2022-10-09 06:37 UTC, undina13 commented on stats_server/src/main/java/ru/practicum/stats_server/HitMapper.java
> +                .timestamp(LocalDateTime.parse(endpointHit.getTimestamp(),
+

2022-10-09 06:40 UTC, undina13 commented on stats_server/src/main/java/ru/practicum/stats_server/HitMapper.java
> +                .timestamp(LocalDateTime.parse(endpointHit.getTimestamp(),
хорошо

2022-10-09 06:43 UTC, undina13 commented on stats_server/src/main/java/ru/practicum/stats_server/service/HitService.java
> +    public EndpointHit createHit(EndpointHit endpointHit) {
Я понимаю, что хочется тесты, мне тоже хочется, но времени сейчас очень мало, а диплом в срок сдать хочется больше. Поэтому пока без тестов

2022-10-09 06:48 UTC, undina13 commented on stats_server/.gitignore
> +HELP.md
готово

2022-10-09 06:55 UTC, undina13 commented on main_server/src/main/java/ru/practicum/main_server/client/BaseClient.java
> +            if (parameters != null) {
совсем про него забыла, спасибо)

2022-10-09 06:55 UTC, undina13 commented on main_server/src/main/java/ru/practicum/main_server/controller/CategoryController.java
> +    @GetMapping()
fix

2022-10-09 06:57 UTC, undina13 commented on main_server/src/main/java/ru/practicum/main_server/controller/ExceptionHandlers.java
> +                .reason("object not found")
fix

2022-10-09 06:57 UTC, undina13 commented on main_server/src/main/java/ru/practicum/main_server/dto/NewCategoryDto.java
> +    private String name;
вопрос к составителям спецификации, нам все дто дали готовые

2022-10-09 06:58 UTC, undina13 commented on main_server/src/main/java/ru/practicum/main_server/model/Participation.java
> +
fix

2022-10-09 06:58 UTC, undina13 commented on main_server/src/main/java/ru/practicum/main_server/model/User.java
> +
fix

2022-10-09 06:59 UTC, undina13 commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +    public EventService(EventRepository eventRepository, ParticipationRepository participationRepository, HitClient hitClient, UserService userService, CategoryRepository categoryRepository, Location
fix

2022-10-09 07:03 UTC, undina13 commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +        if (rangeStart == null) {
окончательно вспомнила тернарник)))

2022-10-09 07:04 UTC, undina13 commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +        if (!(dto.getState().equals(State.PUBLISHED.toString()))) {
InteljIdea ругается так и просит переписать на equals

2022-10-09 08:05 UTC, undina13 commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +        if (adminUpdateEventRequest.getAnnotation() != null) {
Классная подсказка, беру на заметку

2022-10-09 14:16 UTC, undina13 commented on main_server/src/main/java/ru/practicum/main_server/service/ParticipationService.java
> +        if (userId.equals(participation.getRequester().getId())) {
готово

2022-10-09 20:08 UTC, Frilock commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +        if (!(dto.getState().equals(State.PUBLISHED.toString()))) {
А тут обманул, тут Вы строки сравниваете, а не enam поля

2022-10-09 20:08 UTC, Frilock approved these changes
Принято

2022-10-11 06:34 UTC, merged